server:
  port: 8889
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

##eureka.instance.lease-expiration-duration-in-seconds=90
##eureka.instance.lease-renewal-interval-in-seconds=30